# COMPREHENSIVE GLOBAL COUNTRY KEYWORDS
# Support for 195+ countries with geolocation detection

COMPREHENSIVE_COUNTRY_KEYWORDS = {
    # ASIA-PACIFIC (25+ countries)
    "afghanistan": ["afghanistan", "kabul", "taliban", "kabuli"],
    "australia": ["australia", "sydney", "melbourne", "aboriginal", "aussie"],
    "bangladesh": ["bangladesh", "dhaka", "bengali"],
    "bhutan": ["bhutan", "thimphu"],
    "brunei": ["brunei", "bandar seri begawan"],
    "cambodia": ["cambodia", "phnom penh", "khmer"],
    "china": ["china", "beijing", "shanghai", "xi jinping", "yuan", "chinese", "hong kong", "macau"],
    "east timor": ["timor", "dili", "timorese"],
    "fiji": ["fiji", "suva"],
    "india": ["india", "delhi", "mumbai", "bangalore", "hyderabad", "modi", "bjp", "congress", "rupee", "ipl"],
    "indonesia": ["indonesia", "jakarta", "sumatra", "java", "indonesian"],
    "japan": ["japan", "tokyo", "yen", "hiroshima", "osaka", "japanese"],
    "kazakhstan": ["kazakhstan", "astana", "almaty"],
    "korea north": ["north korea", "pyongyang", "kim jong"],
    "korea south": ["south korea", "seoul", "samsung", "korean"],
    "laos": ["laos", "vientiane", "lao"],
    "malaysia": ["malaysia", "kuala lumpur", "malaysian"],
    "maldives": ["maldives", "male"],
    "mongolia": ["mongolia", "ulaanbaatar"],
    "myanmar": ["myanmar", "burma", "yangon", "naypyidaw"],
    "nepal": ["nepal", "kathmandu", "nepali"],
    "pakistan": ["pakistan", "islamabad", "karachi", "lahore", "pakistani"],
    "philippines": ["philippines", "manila", "manila", "philippine"],
    "singapore": ["singapore", "singaporean"],
    "sri lanka": ["sri lanka", "colombo", "ceylon", "sri lankan"],
    "thailand": ["thailand", "bangkok", "thai"],
    "vietnam": ["vietnam", "hanoi", "ho chi minh", "vietnamese"],
    "new zealand": ["new zealand", "auckland", "wellington", "kiwi"],
    "papua new guinea": ["papua new guinea", "port moresby"],
    "solomon islands": ["solomon islands", "honiara"],

    # EUROPE (45+ countries)
    "albania": ["albania", "tirana", "albanian"],
    "andorra": ["andorra", "andorran"],
    "austria": ["austria", "vienna", "austrian"],
    "belarus": ["belarus", "minsk", "belarusian"],
    "belgium": ["belgium", "brussels", "belgian"],
    "bosnia": ["bosnia", "sarajevo", "bosnian"],
    "bulgaria": ["bulgaria", "sofia", "bulgarian"],
    "croatia": ["croatia", "zagreb", "croatian"],
    "cyprus": ["cyprus", "nicosia", "cypriot"],
    "czech republic": ["czech republic", "prague", "czech"],
    "czechoslovakia": ["czechoslovakia"],
    "denmark": ["denmark", "copenhagen", "danish"],
    "estonia": ["estonia", "tallinn", "estonian"],
    "finland": ["finland", "helsinki", "finnish"],
    "france": ["france", "paris", "french", "marseille"],
    "germany": ["germany", "berlin", "munich", "german"],
    "greece": ["greece", "athens", "greek"],
    "hungary": ["hungary", "budapest", "hungarian"],
    "iceland": ["iceland", "reykjavik", "icelandic"],
    "ireland": ["ireland", "dublin", "irish"],
    "italy": ["italy", "rome", "milan", "italian"],
    "kosovo": ["kosovo", "pristina", "kosovar"],
    "latvia": ["latvia", "riga", "latvian"],
    "liechtenstein": ["liechtenstein", "vaduz"],
    "lithuania": ["lithuania", "vilnius", "lithuanian"],
    "luxembourg": ["luxembourg", "luxembourgian"],
    "malta": ["malta", "valletta", "maltese"],
    "moldova": ["moldova", "chisinau", "moldovan"],
    "monaco": ["monaco", "monegasque"],
    "montenegro": ["montenegro", "podgorica", "montenegrin"],
    "netherlands": ["netherlands", "amsterdam", "dutch"],
    "north macedonia": ["north macedonia", "skopje", "macedonian"],
    "norway": ["norway", "oslo", "norwegian"],
    "poland": ["poland", "warsaw", "polish"],
    "portugal": ["portugal", "lisbon", "portuguese"],
    "romania": ["romania", "bucharest", "romanian"],
    "russia": ["russia", "moscow", "putin", "ruble", "kremlin", "russian"],
    "san marino": ["san marino"],
    "serbia": ["serbia", "belgrade", "serbian"],
    "slovakia": ["slovakia", "bratislava", "slovak"],
    "slovenia": ["slovenia", "ljubljana", "slovenian"],
    "spain": ["spain", "madrid", "barcelona", "spanish"],
    "sweden": ["sweden", "stockholm", "swedish"],
    "switzerland": ["switzerland", "zurich", "bern", "swiss"],
    "ukraine": ["ukraine", "kyiv", "ukrainian"],
    "united kingdom": ["uk", "britain", "england", "london", "scotland", "wales", "boris", "parliament", "british"],

    # AFRICA (54 countries)
    "algeria": ["algeria", "algiers", "algerian"],
    "angola": ["angola", "luanda", "angolan"],
    "benin": ["benin", "porto-novo", "beninese"],
    "botswana": ["botswana", "gaborone", "motswana"],
    "burkina faso": ["burkina faso", "ouagadougou", "burkinabe"],
    "burundi": ["burundi", "bujumbura", "burundian"],
    "cameroon": ["cameroon", "yaounde", "cameroonian"],
    "cape verde": ["cape verde", "praia"],
    "central african republic": ["central african republic", "bangui"],
    "chad": ["chad", "ndjamena", "chadian"],
    "comoros": ["comoros", "moroni"],
    "congo": ["congo", "brazzaville", "congolese"],
    "congo democratic republic": ["dr congo", "congo", "kinshasa", "zaire"],
    "cote d'ivoire": ["cote d'ivoire", "ivory coast", "abidjan", "ivorian"],
    "djibouti": ["djibouti", "djiboutian"],
    "egypt": ["egypt", "cairo", "egyptian"],
    "equatorial guinea": ["equatorial guinea"],
    "eritrea": ["eritrea", "asmara", "eritrean"],
    "ethiopia": ["ethiopia", "addis ababa", "ethiopian"],
    "gabon": ["gabon", "libreville", "gabonese"],
    "gambia": ["gambia", "banjul", "gambian"],
    "ghana": ["ghana", "accra", "ghanaian"],
    "guinea": ["guinea", "conakry", "guinean"],
    "guinea-bissau": ["guinea-bissau", "bissau"],
    "kenya": ["kenya", "nairobi", "kenyan"],
    "lesotho": ["lesotho", "maseru"],
    "liberia": ["liberia", "monrovia", "liberian"],
    "libya": ["libya", "tripoli", "benghazi", "libyan"],
    "madagascar": ["madagascar", "antananarivo", "malagasy"],
    "malawi": ["malawi", "lilongwe", "malawian"],
    "mali": ["mali", "bamako", "malian"],
    "mauritania": ["mauritania", "nouakchott", "mauritanian"],
    "mauritius": ["mauritius", "port louis", "mauritian"],
    "morocco": ["morocco", "rabat", "casablanca", "moroccan"],
    "mozambique": ["mozambique", "maputo", "mozambican"],
    "namibia": ["namibia", "windhoek", "namibian"],
    "niger": ["niger", "niamey", "nigerian"],
    "nigeria": ["nigeria", "lagos", "abuja", "nigerian"],
    "rwanda": ["rwanda", "kigali", "rwandan"],
    "sao tome": ["sao tome", "principe"],
    "senegal": ["senegal", "dakar", "senegalese"],
    "seychelles": ["seychelles", "victoria"],
    "sierra leone": ["sierra leone", "freetown", "sierra leonean"],
    "somalia": ["somalia", "mogadishu", "somali"],
    "south africa": ["south africa", "johannesburg", "cape town", "south african"],
    "south sudan": ["south sudan", "juba", "south sudanese"],
    "sudan": ["sudan", "khartoum", "sudanese"],
    "swaziland": ["swaziland", "eswatini", "mbabane"],
    "tanzania": ["tanzania", "dar es salaam", "tanzanian"],
    "togo": ["togo", "lome", "togolese"],
    "tunisia": ["tunisia", "tunis", "tunisian"],
    "uganda": ["uganda", "kampala", "ugandan"],
    "zambia": ["zambia", "lusaka", "zambian"],
    "zimbabwe": ["zimbabwe", "harare", "zimbabwean"],

    # AMERICAS (35+ countries)
    "antigua barbuda": ["antigua barbuda"],
    "argentina": ["argentina", "buenos aires", "argentine"],
    "bahamas": ["bahamas", "nassau", "bahamian"],
    "barbados": ["barbados", "bridgetown", "barbadian"],
    "belize": ["belize", "belmopan", "belizean"],
    "bolivia": ["bolivia", "la paz", "sucre", "bolivian"],
    "brazil": ["brazil", "brasilia", "rio", "sao paulo", "brazilian"],
    "canada": ["canada", "toronto", "vancouver", "ottawa", "canadian"],
    "chile": ["chile", "santiago", "chilean"],
    "colombia": ["colombia", "bogota", "colombian"],
    "costa rica": ["costa rica", "san jose", "costa rican"],
    "cuba": ["cuba", "havana", "cuban"],
    "dominica": ["dominica", "roseau"],
    "dominican republic": ["dominican republic", "santo domingo", "dominican"],
    "ecuador": ["ecuador", "quito", "ecuadorian"],
    "el salvador": ["el salvador", "san salvador", "salvadoran"],
    "grenada": ["grenada", "st. george's"],
    "guatemala": ["guatemala", "guatemala city", "guatemalan"],
    "guyana": ["guyana", "georgetown", "guyanese"],
    "haiti": ["haiti", "port-au-prince", "haitian"],
    "honduras": ["honduras", "tegucigalpa", "honduran"],
    "jamaica": ["jamaica", "kingston", "jamaican"],
    "mexico": ["mexico", "mexico city", "mexican"],
    "nicaragua": ["nicaragua", "managua", "nicaraguan"],
    "panama": ["panama", "panama city", "panamanian"],
    "paraguay": ["paraguay", "asuncion", "paraguayan"],
    "peru": ["peru", "lima", "peruvian"],
    "saint kitts": ["saint kitts", "basseterre"],
    "saint lucia": ["saint lucia", "castries"],
    "saint vincent": ["saint vincent", "kingstown"],
    "suriname": ["suriname", "paramaribo", "surinamese"],
    "trinidad tobago": ["trinidad", "tobago", "port of spain"],
    "usa": ["usa", "america", "us ", "united states", "trump", "biden", "washington", "new york", "california", "dollar", "american"],
    "uruguay": ["uruguay", "montevideo", "uruguayan"],
    "venezuela": ["venezuela", "caracas", "venezuelan"],

    # MIDDLE EAST & CENTRAL ASIA (20+ countries)
    "armenia": ["armenia", "yerevan", "armenian"],
    "azerbaijan": ["azerbaijan", "baku", "azerbaijani"],
    "bahrain": ["bahrain", "manama", "bahraini"],
    "georgia": ["georgia", "tbilisi", "georgian"],
    "iran": ["iran", "tehran", "persian", "iranian"],
    "iraq": ["iraq", "baghdad", "iraqi"],
    "israel": ["israel", "tel aviv", "jerusalem", "israeli"],
    "jordan": ["jordan", "amman", "jordanian"],
    "kuwait": ["kuwait", "kuwait city", "kuwaiti"],
    "kyrgyzstan": ["kyrgyzstan", "bishkek"],
    "lebanon": ["lebanon", "beirut", "lebanese"],
    "oman": ["oman", "muscat", "omani"],
    "qatar": ["qatar", "doha", "qatari"],
    "saudi arabia": ["saudi arabia", "riyadh", "saudi"],
    "syria": ["syria", "damascus", "syrian"],
    "tajikistan": ["tajikistan", "dushanbe"],
    "turkey": ["turkey", "ankara", "istanbul", "turkish"],
    "turkmenistan": ["turkmenistan", "ashgabat"],
    "united arab emirates": ["uae", "dubai", "abu dhabi", "emirate"],
    "uzbekistan": ["uzbekistan", "tashkent"],
    "yemen": ["yemen", "sana'a", "yemeni"],

    # FALLBACK / REGIONS
    "worldwide": ["worldwide", "global", "world"],
    "international": ["international", "global"],
    "africa": ["africa", "african"],
    "asia": ["asia", "asian"],
    "europe": ["europe", "european"],
    "americas": ["americas", "american"],
    "oceania": ["oceania", "pacific"],
}

# Country names for dropdown (sorted)
COUNTRY_LIST = sorted([
    # Worldwide
    "Worldwide", "International",

    # Asia-Pacific
    "Afghanistan", "Australia", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China",
    "East Timor", "Fiji", "India", "Indonesia", "Japan", "Kazakhstan", "Korea North",
    "Korea South", "Laos", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nepal",
    "Pakistan", "Philippines", "Singapore", "Sri Lanka", "Thailand", "Vietnam",
    "New Zealand", "Papua New Guinea", "Solomon Islands",

    # Europe
    "Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia", "Bulgaria",
    "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland", "France",
    "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kosovo", "Latvia",
    "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco",
    "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal",
    "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain",
    "Sweden", "Switzerland", "Ukraine", "United Kingdom",

    # Africa
    "Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cameroon",
    "Cape Verde", "Central African Republic", "Chad", "Comoros", "Congo",
    "Congo Democratic Republic", "Cote d'Ivoire", "Djibouti", "Egypt",
    "Equatorial Guinea", "Eritrea", "Ethiopia", "Gabon", "Gambia", "Ghana",
    "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar",
    "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia",
    "Niger", "Nigeria", "Rwanda", "Sao Tome", "Senegal", "Seychelles",
    "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Swaziland",
    "Tanzania", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe",

    # Americas
    "Antigua Barbuda", "Argentina", "Bahamas", "Barbados", "Belize", "Bolivia",
    "Brazil", "Canada", "Chile", "Colombia", "Costa Rica", "Cuba", "Dominica",
    "Dominican Republic", "Ecuador", "El Salvador", "Grenada", "Guatemala", "Guyana",
    "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay",
    "Peru", "Saint Kitts", "Saint Lucia", "Saint Vincent", "Suriname",
    "Trinidad Tobago", "USA", "Uruguay", "Venezuela",

    # Middle East & Central Asia
    "Armenia", "Azerbaijan", "Bahrain", "Georgia", "Iran", "Iraq", "Israel",
    "Jordan", "Kuwait", "Kyrgyzstan", "Lebanon", "Oman", "Qatar", "Saudi Arabia",
    "Syria", "Tajikistan", "Turkey", "Turkmenistan", "United Arab Emirates",
    "Uzbekistan", "Yemen",

    # Regions
    "Africa", "Asia", "Europe", "Americas", "Oceania"
])
